/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.32.1
// source: src/proto/patient.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = require('./patient_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.PatientGrpcClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.PatientGrpcPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.CreatePatientRequest,
 *   !proto.CreatePatientResponse>}
 */
const methodDescriptor_PatientGrpc_CreatePatient = new grpc.web.MethodDescriptor(
  '/PatientGrpc/CreatePatient',
  grpc.web.MethodType.UNARY,
  proto.CreatePatientRequest,
  proto.CreatePatientResponse,
  /**
   * @param {!proto.CreatePatientRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CreatePatientResponse.deserializeBinary
);


/**
 * @param {!proto.CreatePatientRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CreatePatientResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CreatePatientResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.PatientGrpcClient.prototype.createPatient =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/PatientGrpc/CreatePatient',
      request,
      metadata || {},
      methodDescriptor_PatientGrpc_CreatePatient,
      callback);
};


/**
 * @param {!proto.CreatePatientRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CreatePatientResponse>}
 *     Promise that resolves to the response
 */
proto.PatientGrpcPromiseClient.prototype.createPatient =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/PatientGrpc/CreatePatient',
      request,
      metadata || {},
      methodDescriptor_PatientGrpc_CreatePatient);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.GetPatientsResponse>}
 */
const methodDescriptor_PatientGrpc_GetPatients = new grpc.web.MethodDescriptor(
  '/PatientGrpc/GetPatients',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.GetPatientsResponse,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.GetPatientsResponse.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.GetPatientsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.GetPatientsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.PatientGrpcClient.prototype.getPatients =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/PatientGrpc/GetPatients',
      request,
      metadata || {},
      methodDescriptor_PatientGrpc_GetPatients,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.GetPatientsResponse>}
 *     Promise that resolves to the response
 */
proto.PatientGrpcPromiseClient.prototype.getPatients =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/PatientGrpc/GetPatients',
      request,
      metadata || {},
      methodDescriptor_PatientGrpc_GetPatients);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UploadPatientPhotoRequest,
 *   !proto.UploadPatientPhotoResponse>}
 */
const methodDescriptor_PatientGrpc_UploadPatientPhoto = new grpc.web.MethodDescriptor(
  '/PatientGrpc/UploadPatientPhoto',
  grpc.web.MethodType.UNARY,
  proto.UploadPatientPhotoRequest,
  proto.UploadPatientPhotoResponse,
  /**
   * @param {!proto.UploadPatientPhotoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.UploadPatientPhotoResponse.deserializeBinary
);


/**
 * @param {!proto.UploadPatientPhotoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.UploadPatientPhotoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.UploadPatientPhotoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.PatientGrpcClient.prototype.uploadPatientPhoto =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/PatientGrpc/UploadPatientPhoto',
      request,
      metadata || {},
      methodDescriptor_PatientGrpc_UploadPatientPhoto,
      callback);
};


/**
 * @param {!proto.UploadPatientPhotoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.UploadPatientPhotoResponse>}
 *     Promise that resolves to the response
 */
proto.PatientGrpcPromiseClient.prototype.uploadPatientPhoto =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/PatientGrpc/UploadPatientPhoto',
      request,
      metadata || {},
      methodDescriptor_PatientGrpc_UploadPatientPhoto);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UpdatePatientRequest,
 *   !proto.UpdatePatientResponse>}
 */
const methodDescriptor_PatientGrpc_UpdatePatient = new grpc.web.MethodDescriptor(
  '/PatientGrpc/UpdatePatient',
  grpc.web.MethodType.UNARY,
  proto.UpdatePatientRequest,
  proto.UpdatePatientResponse,
  /**
   * @param {!proto.UpdatePatientRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.UpdatePatientResponse.deserializeBinary
);


/**
 * @param {!proto.UpdatePatientRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.UpdatePatientResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.UpdatePatientResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.PatientGrpcClient.prototype.updatePatient =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/PatientGrpc/UpdatePatient',
      request,
      metadata || {},
      methodDescriptor_PatientGrpc_UpdatePatient,
      callback);
};


/**
 * @param {!proto.UpdatePatientRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.UpdatePatientResponse>}
 *     Promise that resolves to the response
 */
proto.PatientGrpcPromiseClient.prototype.updatePatient =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/PatientGrpc/UpdatePatient',
      request,
      metadata || {},
      methodDescriptor_PatientGrpc_UpdatePatient);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.GetPatientByIdRequest,
 *   !proto.GetPatientByIdResponse>}
 */
const methodDescriptor_PatientGrpc_GetPatientById = new grpc.web.MethodDescriptor(
  '/PatientGrpc/GetPatientById',
  grpc.web.MethodType.UNARY,
  proto.GetPatientByIdRequest,
  proto.GetPatientByIdResponse,
  /**
   * @param {!proto.GetPatientByIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.GetPatientByIdResponse.deserializeBinary
);


/**
 * @param {!proto.GetPatientByIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.GetPatientByIdResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.GetPatientByIdResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.PatientGrpcClient.prototype.getPatientById =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/PatientGrpc/GetPatientById',
      request,
      metadata || {},
      methodDescriptor_PatientGrpc_GetPatientById,
      callback);
};


/**
 * @param {!proto.GetPatientByIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.GetPatientByIdResponse>}
 *     Promise that resolves to the response
 */
proto.PatientGrpcPromiseClient.prototype.getPatientById =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/PatientGrpc/GetPatientById',
      request,
      metadata || {},
      methodDescriptor_PatientGrpc_GetPatientById);
};


module.exports = proto;

